#!/bin/bash

alias sz='source ~/.zshrc'
alias c='clear'
alias e='exit'

# Allow aliases to be with sudo
alias sudo="sudo "
alias apt-get="sudo apt-get"

alias ls="ls -pG"
alias ll="ls -lph"
alias l.="ls -d .[^.]*"
alias ll.="ll -d .[^.]*"

alias grep="grep -i"

alias path='echo -e ${PATH//:/\\n}'

# navigation
alias cdd="cd ~/.dotfiles/"
alias cdg="cd ~/p/go/src/github.com/adamreese/"

# git
alias gaa='git add --all'
alias gap='git add -p'
alias gfa='git fetch --all'
alias gpl='git pull'
alias gs='git status -s'

# bundle
alias be='bundle exec'
alias bi='bundle install'
alias bil='bundle install --local'
alias bu='bundle update'

# rails
alias bake='bundle exec rake'

# bundle rspec
alias br='bundle exec rspec'
alias brff='bundle exec rspec --fail-fast'

# bundle guard
alias beg='bundle exec guard'

# Open file in existing MacVim window
alias gvim="open -a MacVim"
alias mvim="open -a MacVim"
alias v="mvim"

# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Enhanced WHOIS lookups
alias whois="whois -h whois-servers.net"

# View logs
alias tfl='tail -Fn30 log/*.log'

# Split comma or colin separated data onto separate lines
alias -g S="| tr ',:' '\n'"

alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L="| less"

alias rethinkdb.start='launchctl load /usr/local/opt/rethinkdb/homebrew.mxcl.rethinkdb.plist'
alias rethinkdb.stop='launchctl unload /usr/local/opt/rethinkdb/homebrew.mxcl.rethinkdb.plist'

alias postgres.start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias postgres.stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
alias postgres.restart='postgres.stop && sleep 1 && postgres.start'

alias update='brew update; brew upgrade; brew cleanup; npm update npm -g; npm update -g; gem update --system; gem update'
