#!/usr/bin/env bash

# Shortcuts
alias c='clear'
alias e='exit'
alias :q='exit'

# Allow aliases to be with sudo
alias sudo='sudo '
alias apt-get='sudo apt-get'

alias ls='ls -pG'
alias ll='ls -lph'

# Perform case insensitive matching
alias grep='grep -i'

alias agp='ag --pager="less -iFMRSX"'

# github
alias gh='hub browse'
alias pr='hub pull-request'

# IP addresses
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias localip='ipconfig getifaddr en1'
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Enhanced WHOIS lookups
alias whois="whois -h whois-servers.net"

# View logs
alias tfl='tail -Fn30 log/*.log'

# zsh specific command aliases
if [ -n "$ZSH_VERSION" ]; then

  # Split comma or colin separated data onto separate lines
  alias -g S="| tr ',:' '\n'"

  alias -g H='| head'
  alias -g T='| tail'
  alias -g G='| grep'
  alias -g L="| less"
fi

# osx specific command aliases
if [[ $(uname -s) = "Darwin" ]]; then

  # bundle
  alias be='bundle-exec-hack'
  alias bi='bundle-hack install'
  alias beg='be guard'
  alias bil='bundle install --local'
  alias br='be rspec'
  alias brff='be rspec --fail-fast'

  # Show/hide hidden files in Finder
  alias show='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'
  alias hide='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'

  # Update and cleanup brew
  alias bubu='brew update && brew upgrade && brew cleanup'
fi
