#!/bin/bash

# bash_config

## Editor
if [[ -s $(which mvim) ]]; then
  export EDITOR=mvim
else
  export EDITOR=vim
fi


# Ignore duplicate commands in the history
export HISTCONTROL=ignoredups

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=10000

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=10000

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Export PhantomJS bin location (be explicit in case Homebrew is not installed
# in the default location)
export PHANTOMJS_BIN="$(brew --prefix)/bin/phantomjs"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Java_home set for pentaho
export JAVA_HOME=$(/usr/libexec/java_home)

# Ruby tweaks
if [[ -z $(ruby -W0 -e "print RUBY_VERSION" | grep 2\.) ]]; then
  export RUBY_FREE_MIN=500000
  export RUBY_HEAP_MIN_SLOTS=40000
else
  export RUBY_GC_MALLOC_LIMIT=1000000000
  export RUBY_GC_HEAP_FREE_SLOTS=1000000000
  export RUBY_GC_HEAP_FREE_SLOTS=500000
fi

export HISTFILESIZE=9999
export HISTSIZE=9999

export LESS_TERMCAP_mb=$(printf "\e[2;31m")
export LESS_TERMCAP_md=$(printf "\e[1;31m")
export LESS_TERMCAP_me=$(printf "\e[0m")
export LESS_TERMCAP_se=$(printf "\e[0m")
export LESS_TERMCAP_so=$(printf "\e[1;44;33m")
export LESS_TERMCAP_ue=$(printf "\e[0m")
export LESS_TERMCAP_us=$(printf "\e[1;32m")
