tap "grain-lang/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "linuxkit/linuxkit"
tap "michaeleisel/zld"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
tap "shipyard-run/repo"
tap "tinygo-org/tools"
tap "universal-ctags/universal-ctags"
# Run your GitHub Actions locally 🚀
brew "act"
# GNU database manager
brew "gdbm"
# YAML Parser
brew "libyaml"
# Library for command-line editing
brew "readline"
# Automate deployment, configuration, and upgrading
brew "ansible"
# Library for manipulating PNG images
brew "libpng"
# Spell checker with better logic than ispell
brew "aspell"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Collection of portable C++ source libraries
brew "boost"
# Official Amazon AWS command-line interface
brew "awscli"
# Microsoft Azure CLI 2.0
brew "azure-cli"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Bash shell debugger
brew "bashdb"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Compiler infrastructure and toolchain library for WebAssembly
brew "binaryen"
# Parser generator
brew "bison"
# Portable Foreign Function Interface library
brew "libffi"
# Next-gen compiler infrastructure
brew "llvm"
# C/C++/ObjC language server
brew "ccls"
# Tool to obtain certs from Let's Encrypt and autoenable HTTPS
brew "certbot"
# Testing and linting Helm charts
brew "chart-testing"
# Enables you to reproduce the CircleCI environment locally
brew "circleci"
# Color-highlighted diff(1) output
brew "colordiff"
# Tool for service discovery, monitoring and configuration
brew "consul"
# Generic template rendering and notifications with Consul
brew "consul-template"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Get, unpack, build, and install modules from CPAN
brew "cpanminus"
# Tool for browsing source code
brew "cscope"
# C library implementing the SSH2 protocol
brew "libssh2"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# POSIX-compliant descendant of NetBSD's ash (the Almquist SHell)
brew "dash"
# Good-lookin' diffs with diff-highlight and more
brew "diff-so-fancy"
# File comparison utilities
brew "diffutils"
# Lightweight DNS forwarder and DHCP server
brew "dnsmasq"
# XML vocabulary to create presentation-neutral documents
brew "docbook-xsl"
# Command-line DNS client
brew "dog"
# Utility to bundle libraries into executables for macOS
brew "dylibbundler"
# Perl compatible regular expressions library with a new API
brew "pcre2"
# Maintain consistent coding style between multiple editors
brew "editorconfig"
# Run arbitrary commands when files change
brew "entr"
# Modern replacement for 'ls'
brew "exa"
# Zero-conf load balancing HTTP(S) router
brew "fabio"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Command-line outline and bitmap font editor/converter
brew "fontforge"
# Terminal JSON viewer
brew "fx"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU awk utility
brew "gawk"
# GitHub command-line tool
brew "gh"
# Work on GitHub issues on the command-line
brew "ghi"
# Remote repository management made easy
brew "ghq"
# Distributed revision control system
brew "git"
# Enable transparent encryption/decryption of files in a git repo
brew "git-crypt"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Small git utilities
brew "git-extras"
# Git extension for versioning large files
brew "git-lfs"
# Render markdown on the CLI
brew "glow"
# Command-line option parsing utility
brew "gnu-getopt"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU version of the tar archiving utility
brew "gnu-tar"
# GNU implementation of time utility
brew "gnu-time"
# GNU implementation of which utility
brew "gnu-which"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Fast linters runner for Go
brew "golangci-lint"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# GNU grep, egrep and fgrep
brew "grep"
# GitHub Markdown previewer
brew "grip"
# Smarter Dockerfile linter to validate best practices
brew "hadolint"
# Powerful, lightweight programming language
brew "lua"
# Convert source code to formatted text with syntax highlighting
brew "highlight"
# Command-line tools for OpenPGP-related operations
brew "hopenpgp-tools"
# Improved top (interactive process viewer)
brew "htop"
# Add GitHub support to git on the command-line
brew "hub"
# Configurable static site generator
brew "hugo"
# Command-line benchmarking tool
brew "hyperfine"
# Get events and tasks from the macOS calendar database
brew "ical-buddy"
# Improved colored diff
brew "icdiff"
# CLI for managing resources in InfluxDB v2
brew "influxdb-cli"
# C library for encoding, decoding, and manipulating JSON
brew "jansson"
# Regular expressions library
brew "oniguruma"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Handy way to save and run project-specific commands
brew "just"
# Run local Kubernetes cluster in Docker
brew "kind"
# Network authentication protocol
brew "krb5"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Tool that can switch between kubectl contexts easily and create aliases
brew "kubectx"
# Let's Encrypt client and ACME library
brew "lego"
# Pager program similar to more
brew "less"
# Input filter for the pager less
brew "lesspipe"
# Asynchronous event library
brew "libev"
# C implementation of a Sass compiler
brew "libsass"
# Library for processing keyboard entry from the terminal
brew "libtermkey"
# C library for manipulating Yubico one-time passwords
brew "libyubikey"
# C library for reading, creating, and modifying zip archives
brew "libzip"
# Emulator for x86 and PowerPC
brew "qemu"
# Linux virtual machines
brew "lima"
# Powerful, lightweight programming language
brew "lua@5.3"
# Package manager for the Lua programming language
brew "luarocks"
# Bare libuv bindings for lua
brew "luv"
# Swiss Army Knife for macOS
brew "m-cli"
# Utility for directing compilation
brew "make"
# Mac App Store command-line interface
brew "mas"
# Scalable distributed version control system
brew "mercurial"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Collection of tools that nobody wrote when UNIX was young
brew "moreutils"
# 'traceroute' and 'ping' in a single tool
brew "mtr"
# Parser generator tool and incremental parsing library
brew "tree-sitter"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx"
# Small build system for use with gyp or CMake
brew "ninja"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node"
# Distributed, Highly Available, Datacenter-Aware Scheduler
brew "nomad"
# OCaml package manager
brew "opam"
# Generate clients, server & docs from an OpenAPI spec (v2, v3)
brew "openapi-generator"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Tool for creating identical machine images for multiple platforms
brew "packer"
# PostgreSQL syntax beautifier
brew "pgformatter"
# Display the PID number for a given process name
brew "pidof"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# User-friendly, console-based viewer for Info documents
brew "pinfo"
# Object-relational database system
brew "postgresql"
# Object-relational database system
brew "postgresql@12"
# Monitor data's progress through a pipe
brew "pv"
# Interpreted, interactive, object-oriented programming language
brew "python@3.8"
# Cross-platform application and UI framework
brew "qt"
# File browser
brew "ranger"
# Reattach process (e.g., tmux) to background
brew "reattach-to-user-namespace"
# Persistent key-value database, with built-in net interface
brew "redis"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Utility that provides fast incremental file transfer
brew "rsync"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Experimental Rust compiler front-end for IDEs
brew "rust-analyzer"
# Rust toolchain installer
brew "rustup-init"
# Wrapper around libsass that helps to create command-line apps
brew "sassc"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# HTTP regression testing and benchmarking utility
brew "siege"
# SOcket CAT: netcat on steroids
brew "socat"
# Source-code syntax highlighter
brew "source-highlight"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Clean C library for processing UTF-8 Unicode data
brew "utf8proc"
# Version control system designed to be a better CVS
brew "subversion"
# Formatting tool for reformatting Swift code
brew "swiftformat"
# Tool to enforce Swift style and conventions
brew "swiftlint"
# Open source continuous file synchronization application
brew "syncthing"
# Send macOS User Notifications from the command-line
brew "terminal-notifier"
# Tool to build, change, and version infrastructure
brew "terraform"
# Multi-platform code-search similar to ack and ag
brew "the_platinum_searcher"
# Code-search similar to ack
brew "the_silver_searcher"
# Text interface for Git repositories
brew "tig"
# Terminal multiplexer
brew "tmux"
# Modern reverse proxy
brew "traefik"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Source code beautifier
brew "uncrustify"
# Google's JavaScript engine
brew "v8"
# Secures, stores, and tightly controls access to secrets
brew "vault"
# Vi 'workalike' with many additional features
brew "vim"
# Web Assembly Binary Toolkit
brew "wabt"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Tool for managing your YubiKey configuration
brew "ykman"
# YubiKey personalization library and tool
brew "ykpers"
# Process YAML documents from the CLI
brew "yq"
# Programming language designed for robustness, optimality, and clarity
brew "zig"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Levant
brew "hashicorp/tap/levant"
# Nomad Pack
brew "hashicorp/tap/nomad-pack"
# Lightweight Linux distribution tool
brew "linuxkit/linuxkit/linuxkit", args: ["HEAD"]
# A faster version of ld, Apple's linker
brew "michaeleisel/zld/zld"
# Massdrop Firmware Loader
brew "qmk/qmk/mdloader"
# Quantum Mechanical Keyboard (QMK) Firmware
brew "qmk/qmk/qmk"
brew "shipyard-run/repo/shipyard"
# TinyGo is a Go compiler for small places. Microcontrollers, WebAssembly, and command-line tools. Based on LLVM.
brew "tinygo-org/tools/tinygo"
# Maintained ctags implementation
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line helper for the 1Password password manager
cask "1password-cli"
# GPU-accelerated terminal emulator
cask "alacritty"
# Web browser focusing on privacy
cask "brave-browser"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker"
# Developer platform
cask "dotnet-sdk"
# Web browser
cask "firefox"
cask "font-dejavu-sans-mono-nerd-font"
cask "font-fira-code"
cask "font-hack"
cask "font-input"
cask "font-iosevka-nerd-font"
# Typeface made for developers
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
# Monospaced variant of "San Francisco" by Apple
cask "font-sf-mono"
cask "font-source-code-pro"
# Web browser
cask "google-chrome"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "google-cloud-sdk"
# Tools to protect your files
cask "gpg-suite-no-mail"
# Packaged Grain binary, including the compiler, runtime & stdlib
cask "grain"
# Desktop automation application
cask "hammerspoon"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Keyboard customizer
cask "karabiner-elements"
# GPU-based terminal emulator
cask "kitty"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Open source implementation of Microsoft's .NET Framework
cask "mono-mdk"
# Cloud storage client
cask "onedrive"
# Toolbox companion for QMK Firmware
cask "qmk-toolbox"
# Imaging utility to install operating systems to a microSD card
cask "raspberry-pi-imager"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Virtual machines UI using QEMU
cask "utm"
# Open-source code editor
cask "visual-studio-code"
# Video communication and virtual meeting platform
cask "zoom"
